---
title: "Exercise 1"
author: "Oleg Kartavtsev"
date: "5/9/2022"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Necessary Package Installation
```{r 0}
#install.packages('ggraph')
#install.packages('tidygraph')
#install.packages('dplyr')
#install.packages('igraph')
```

## Importing the File
```{r 1}
#reading the library 
library(igraph)
library(dplyr)
library(tidygraph)
library(ggraph)
library(readr)
library(tidyverse)
connections <- read_csv("Connections.csv")

#getting rid of NA values in the "Company" column
df <- connections[!(is.na(connections$Company) | connections$Company==""), ]
```

## Getting Total Count of all Connections
```{r 2}
connections %>% count()
```

## Getting Count of all Connection by Company Name
```{r 3}
df %>% 
  count(Company) %>% 
  arrange(-n)
```

## Coding the Graph
```{r 4}
# Creating the label - using both full first and last names to avoid potential duplicates
df$label <- paste(df$`First Name`, df$`Last Name`)

# Creating nodes
nodes <- df %>% select(c("label", "Company"))
nodes <- nodes %>% rowid_to_column("id")

# Creating edges
edges <- df %>% select(c(label, Company)) %>% 
  left_join(nodes %>% select(c(id,label)), by = c("label"="label"))
edges <- edges %>% left_join(edges, by = "Company", keep=FALSE) %>% 
  select(c("id.x", "id.y", "Company")) %>% 
  filter(id.x!=id.y)
colnames(edges) <- c("x", "y", "Company")

#let's check what we got
edges %>% head(10)
```




## Plotting the results
```{r plot}
graph <- tbl_graph(edges = edges, nodes=nodes, directed = FALSE)
ggraph(graph, layout = "graphopt") + 
  geom_edge_link(aes(color = Company), show.legend = FALSE) + 
  geom_node_point()+
  theme_graph()
```